# Based partially on Alyxia's work, thanks so much!

name: Release
on:
  push:
    tags:
      - v*

env:
  FORCE_COLOR: true

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go dependencies
        run: go get -v

      - name: Build Cli
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -tags "static cli" -ldflags "-s -w -X 'velocityinstaller/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)' -X 'velocityinstaller/buildinfo.InstallerTag=${{ github.ref_name }}'" -o VelocityInstallerCli-linux

      - name: Update executable
        run: chmod +x VelocityInstallerCli-linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VelocityInstaller-linux
          path: VelocityInstallerCli-linux


  build-mac:
    runs-on: macos-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: brew install pkg-config sdl2

      - name: Install Go dependencies
        run: go get -v

      - name: Build
        run: CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -v -tags static -ldflags "-s -w -X 'velocityinstaller/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)' -X 'velocityinstaller/buildinfo.InstallerTag=${{ github.ref_name }}'" -o VelocityInstaller

      - name: Update executable
        run: chmod +x VelocityInstaller

      - name: Generate MacOS bundle
        run: |
          mkdir -p VelocityInstaller.app/Contents/MacOS
          mkdir -p VelocityInstaller.app/Contents/Resources
          cp macos/Info.plist VelocityInstaller.app/Contents/Info.plist
          mv VelocityInstaller VelocityInstaller.app/Contents/MacOS/VelocityInstaller
          cp macos/icon.icns VelocityInstaller.app/Contents/Resources/icon.icns
          zip -r VelocityInstaller.MacOS.zip VelocityInstaller.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VelocityInstaller-macos
          path: VelocityInstaller.MacOS.zip


  build-windows:
    runs-on: windows-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\go-build
            ~\go\pkg\mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2

      - name: Install Windows dependencies
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm git mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-go
          export GOROOT=/mingw64/lib/go
          export GOPATH=/mingw64

      - name: Install Go dependencies
        shell: msys2 {0}
        run: |
          export GOROOT=/mingw64/lib/go
          export GOPATH=/mingw64
          go get -v
          go install github.com/tc-hib/go-winres@latest

      - name: Build Gui
        shell: msys2 {0}
        run: |
          export GOROOT=/mingw64/lib/go
          export GOPATH=/mingw64
          go-winres make --product-version "git-tag"
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -v -tags static -ldflags "-s -w -H=windowsgui -extldflags=-static -X 'velocityinstaller/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)' -X 'velocityinstaller/buildinfo.InstallerTag=${{ github.ref_name }}'" -o VelocityInstaller.exe

      - name: Build i386 Cli
        shell: msys2 {0}
        run: |
          export GOROOT=/mingw64/lib/go
          export GOPATH=/mingw64
          CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -v -tags "static cli" -ldflags "-s -w -extldflags=-static -X 'velocityinstaller/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)' -X 'velocityinstaller/buildinfo.InstallerTag=${{ github.ref_name }}'" -o VelocityInstallerCli.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VelocityInstaller-windows
          path: |
            VelocityInstaller.exe
            VelocityInstallerCli.exe


  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-mac, build-windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: VelocityInstaller-linux
          path: linux

      - uses: actions/download-artifact@v4
        with:
          name: VelocityInstaller-macos
          path: macos

      - uses: actions/download-artifact@v4
        with:
          name: VelocityInstaller-windows
          path: windows

      - name: Create the release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          prerelease: false
          draft: false
          files: |
            linux/VelocityInstallerCli-linux
            macos/VelocityInstaller.MacOS.zip
            windows/VelocityInstalle*.exe